### ISSUE TITLE
Lint messages have ".git" appended to filenames 

### ISSUE THREAD

**Issue by chrstphrchvz** [d9705996/perl-toolbox#10] opened 2018-11-13 07:24 UTC
Using VS Code 1.29.0 on macOS and Windows.

I mainly work on projects in git repositories, so I'm wondering if this is caused partly by VS Code's git extension springing into action when files are saved.

When the perlcritic output is displayed in Problems tab, filenames often have `.git` appended, so clicking a message displays an empty file rather than the line on the correct file. This only seems to affect perlcritic `Lint:` messages and not `Syntax:` messages. Here is a screenshot when a file is first opened:

![annotation 2018-11-13 010253](https://user-images.githubusercontent.com/7941193/48396590-9021d800-e6e0-11e8-8955-50ea5ec037a7.png)

Then, when I save it , the new linting messages show correctly but the old messages for the bogus `.git` file remain (as an example I added `''` to receive the message `Lint: CRUEL: Quotes used with a string containing no non-whitespace characters`):

![annotation 2018-11-13 011044](https://user-images.githubusercontent.com/7941193/48396789-37067400-e6e1-11e8-81a0-1193a510a97d.png)

**Comment by d9705996** [comment] 2018-11-14 09:35
@chrstphrchvz - I have tested locally and can replicate the issue with v.1.29.0.  Do you know if this only started happening for you when you have updated to 1.29.0?

**Comment by chrstphrchvz** [comment] 2018-11-14 10:59
It happens on 1.28.2 as well

**Comment by d9705996** [comment] 2018-11-16 14:15
I'm struggling to reliably replicate the fault.  It seems to happen at random so testing is a nightmare.  Any help with either a reliable way to replicate or any PRs welcome

**Comment by chrstphrchvz** [comment] 2018-11-16 15:32
Indeed this seems hard to "break" in a consistent/reproducible manner.

It seems like the lint messages tend to only appear under whichever file was least recently opened. Saving multiple files simultaneously is another way to trigger this or a related issue, but that is not reliable either.

**Comment by Eitz** [comment] 2019-02-05 11:27
I am having the same problem as well... No new info, though.

**Comment by afgit** [comment] 2019-04-30 15:02
Same problem here.
I "solved" it by disabling linting in perl-toolbox and using [sfodje's perlcritic extension ](https://github.com/sfodje/perlcritic) instead.

**Comment by d9705996** [comment] 2019-06-04 10:27
looks like a similar issue in https://github.com/sfodje/perlcritic/issues/1

**Comment by d9705996** [comment] 2019-06-05 07:20
SHould be resolved in 5ecd8374cd28ec82ca2fb4762dc960bc7ea72ecf

**Comment by d9705996** [comment] 2019-06-05 07:33
perl-toolbox 1.3.2 released on marketplace with fix

**Comment by d9705996** [comment] 2019-06-05 07:36
After testing outside of developer extension the issue is not resolved.  Will need to review

**Comment by d9705996** [comment] 2020-01-10 05:48
v1.4.0 should fix

**Closed as completed** 2020-01-10 05:48 UTC
Labels: bug, help wanted
